In [65]:
import cv2
import numpy as np
# from shapely.geometry import Point
# from shapely.geometry.polygon import Polygon

In [66]:
arucoDict = cv2.aruco.getPredefinedDictionary(cv2.aruco.DICT_4X4_250)
parameters =  cv2.aruco.DetectorParameters()
detector = cv2.aruco.ArucoDetector(arucoDict, parameters)

image = cv2.imread("4x4_riyal.png")
(corners_ndarray, ids, rejectedCandidates) = detector.detectMarkers(image)

In [67]:
corners = []
for corner in corners_ndarray:
    corners.extend([int(j) for j in corner.flatten()])

In [46]:
image.shape

(941, 2038, 3)

In [72]:
# corners = [160, 283, 229, 283, 229, 352, 160, 352, 454, 675, 523, 675, 523, 744, 454, 744, 62, 87, 131, 87, 131, 156, 62, 156, 160, 87, 229, 87, 229, 156, 160, 156, 258, 87, 327, 87, 327, 156, 258, 156, 356, 87, 425, 87, 425, 156, 356, 156, 454, 283, 523, 283, 523, 352, 454, 352, 356, 283, 425, 283, 425, 352, 356, 352, 258, 283, 327, 283, 327, 352, 258, 352, 356, 675, 425, 675, 425, 744, 356, 744, 62, 283, 131, 283, 131, 352, 62, 352, 454, 87, 523, 87, 523, 156, 454, 156, 454, 185, 523, 185, 523, 254, 454, 254, 356, 185, 425, 185, 425, 254, 356, 254, 258, 185, 327, 185, 327, 254, 258, 254, 160, 185, 229, 185, 229, 254, 160, 254, 62, 185, 131, 185, 131, 254, 62, 254, 258, 381, 327, 381, 327, 450, 258, 450, 258, 479, 327, 479, 327, 548, 258, 548, 356, 479, 425, 479, 425, 548, 356, 548, 454, 479, 523, 479, 523, 548, 454, 548, 62, 577, 131, 577, 131, 646, 62, 646, 160, 577, 229, 577, 229, 646, 160, 646, 258, 577, 327, 577, 327, 646, 258, 646, 454, 381, 523, 381, 523, 450, 454, 450, 356, 381, 425, 381, 425, 450, 356, 450, 160, 381, 229, 381, 229, 450, 160, 450, 62, 381, 131, 381, 131, 450, 62, 450, 356, 577, 425, 577, 425, 646, 356, 646, 454, 577, 523, 577, 523, 646, 454, 646, 62, 675, 131, 675, 131, 744, 62, 744, 160, 675, 229, 675, 229, 744, 160, 744, 258, 675, 327, 675, 327, 744, 258, 744, 62, 479, 131, 479, 131, 548, 62, 548, 160, 479, 229, 479, 229, 548, 160, 548]
print(corners)

[1687, 387, 1893, 341, 1947, 535, 1733, 572, 1018, 386, 1188, 423, 1156, 596, 984, 560, 676, 420, 831, 422, 820, 596, 651, 591]


In [13]:
len(corners)/8

37.0

In [ ]:
corners[8:16]

In [68]:
num_boxes = len(corners)//8
boxes_list = list()
for i in range(num_boxes):
    cornerset = corners[8*i:8*i+8]
    v1 = (cornerset[1], cornerset[0])
    v2 = (cornerset[3], cornerset[2])
    v3 = (cornerset[5], cornerset[4])
    v4 = (cornerset[7], cornerset[6])
    # v1 and v4 have same abscissa
    # v2 and v3 have same abscissa
    box = (v1, v2, v3, v4)
    boxes_list.append(box)

In [73]:
print(boxes_list)

[((387, 1687), (341, 1893), (535, 1947), (572, 1733)), ((386, 1018), (423, 1188), (596, 1156), (560, 984)), ((420, 676), (422, 831), (596, 820), (591, 651))]


In [76]:
def generate_image(img_shape, boxes):
    # ((577, 62), (577, 131), (646, 131), (646, 62))
    image = np.ones(img_shape, dtype=np.int32)*255
    
    for box in boxes:
        # print(box)
        # list(box)
        # polygon = Polygon(list(box))
        # v1, v2, v3, v4 = box
        vertex_array = np.array([[v[1], v[0]] for v in box])
        print(vertex_array)

        cv2.fillPoly(image, [vertex_array], 0)

    return image

In [77]:

img = generate_image((941, 2038), boxes_list)

[[1687  387]
 [1893  341]
 [1947  535]
 [1733  572]]
[[1018  386]
 [1188  423]
 [1156  596]
 [ 984  560]]
[[676 420]
 [831 422]
 [820 596]
 [651 591]]


In [ ]:
type(img)

In [ ]:
print(0 in img)

In [78]:
# image = np.ones((842, 595), dtype=np.int32) * 255
cv2.imwrite("trial.jpg", img)
# cv2.imshow("trial", img)
# cv2.waitKey(5000)
# cv2.destroyWindow("trial")


True

In [ ]:
print(corners," space ")

In [ ]:
print(ids.flatten())